# Generated by Django 4.2.5 on 2023-10-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Finance_Assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='finance',
            field=models.CharField(default='income', max_length=20),
        ),
    ]
