# Generated by Django 4.2.5 on 2023-10-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Finance_Assistant', '0013_alter_incomerecord_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
