# Generated by Django 4.2.5 on 2023-10-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    #dependencies = [
      #  ('Personal_Finance_Assistant', '0003_alter_user_info_email'),
    #]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocksymbol', models.CharField(max_length=15)),
                ('stockname', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal_Finance_Assistant.user_info')),
            ],
        ),
    ]
