# Generated by Django 4.2.5 on 2023-10-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_portfolio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='stockname',
            field=models.CharField(max_length=110),
        ),
    ]
