# Generated by Django 4.2.5 on 2023-10-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_rename_portfolio_stockportfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockportfolio',
            name='user',
        ),
    ]
