# Generated by Django 4.2.5 on 2023-10-03 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0013_alter_stockportfolio_stockname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='stockname',
            field=models.CharField(max_length=110),
        ),
    ]
