# Generated by Django 4.2.5 on 2023-10-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_stockportfolio_user_alter_stockportfolio_stockname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='stockname',
            field=models.CharField(max_length=100),
        ),
    ]
