# Generated by Django 4.2.5 on 2023-10-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_stockportfolio_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='current_price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
