# Generated by Django 4.2.5 on 2023-10-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_stockportfolio_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
    ]
